// <auto-generated />
using BethanysPieShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BethanysPieShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211117082351_AddingNoteFieldOnPie")]
    partial class AddingNoteFieldOnPie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BethanysPieShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Italian",
                            Description = "Cake de pizza italien"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Indian",
                            Description = "Delice du l'inde aux saveurs incomparables"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Cameroonian",
                            Description = "Les tchops du pays qui reveil le spirit"
                        });
                });

            modelBuilder.Entity("BethanysPieShop.Models.Pie", b =>
                {
                    b.Property<int>("PieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Notes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = 1,
                            CategoryId = 3,
                            InStock = false,
                            IsPieOfTheWeek = false,
                            Name = "Baskess",
                            Notes = 0m,
                            Price = 22m,
                            ShortDescription = "Cake de pizza italien"
                        },
                        new
                        {
                            PieId = 2,
                            CategoryId = 3,
                            InStock = false,
                            IsPieOfTheWeek = false,
                            Name = "Cake Krus",
                            Notes = 0m,
                            Price = 105m,
                            ShortDescription = "Delice du l'inde aux saveurs incomparables"
                        },
                        new
                        {
                            PieId = 3,
                            CategoryId = 2,
                            InStock = false,
                            IsPieOfTheWeek = false,
                            Name = "Ndole Lave",
                            Notes = 0m,
                            Price = 43m,
                            ShortDescription = "Les tchops du pays qui reveil le spirit"
                        },
                        new
                        {
                            PieId = 4,
                            CategoryId = 1,
                            InStock = false,
                            IsPieOfTheWeek = false,
                            Name = "Pizza Scott's",
                            Notes = 0m,
                            Price = 25m,
                            ShortDescription = "Les tchops du pays qui reveil le spirit"
                        },
                        new
                        {
                            PieId = 5,
                            CategoryId = 2,
                            InStock = false,
                            IsPieOfTheWeek = false,
                            Name = "Manioc Tubercule",
                            Notes = 0m,
                            Price = 500m,
                            ShortDescription = "Les tchops du pays qui reveil le spirit"
                        });
                });

            modelBuilder.Entity("BethanysPieShop.Models.Pie", b =>
                {
                    b.HasOne("BethanysPieShop.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
